channels:
- conda-forge
dependencies:
- python=3.9.18
- pip<=23.3
- pip:
  - mlflow==2.9.2
  - cloudpickle==2.2.1
  - numpy==1.26.1
  - packaging==23.2
  - psutil==5.9.6
  - pyyaml==6.0.1
  - scikit-learn==1.3.2
  - scipy==1.11.3
name: mlflow-env
